const keywordMappings = {
  Altbier: ["traditional", "malty", "copper", "altbier"],
  "Australian Sparkling Ale": [
    "crisp",
    "fruity",
    "refreshing",
    "ale",
    "australian",
  ],
  "Barleywine - American": ["strong", "hoppy", "caramel", "barleywine"],
  "Barleywine - English": ["rich", "balanced", "toffee", "barleywine"],
  "Barleywine - Other": ["complex", "aged", "robust", "barleywine"],
  "Belgian Blonde": ["spicy", "aromatic", "golden"],
  "Belgian Dubbel": ["dark", "fruity", "abbey"],
  "Belgian Enkel / Patersbier": ["light", "delicate", "monastery"],
  "Belgian Quadrupel": ["strong", "dark", "quad"],
  "Belgian Strong Dark Ale": ["complex", "warming", "Trappist"],
  "Belgian Strong Golden Ale": ["strong", "golden", "effervescent"],
  "Belgian Tripel": ["strong", "fruity", "spicy"],
  "Bitter - Best": ["balanced", "malty", "traditional"],
  "Bitter - Extra Special / Strong (ESB)": ["robust", "caramel", "English"],
  "Bitter - Session / Ordinary": ["easy-drinking", "hoppy", "British"],
  "Biere de Champagne / Biere Brut": ["sparkling", "dry", "celebratory"],
  "Black & Tan": ["layered", "dark/light", "mix"],
  "Blonde Ale": ["smooth", "light", "versatile"],
  "Bock - Doppelbock": ["strong", "malty", "dark"],
  "Bock - Eisbock": ["intense", "frozen", "concentrated"],
  "Bock - Hell / Maibock / Lentebock": ["pale", "balanced", "spring"],
  "Bock - Single / Traditional": ["traditional", "malt-forward", "smooth"],
  "Bock - Weizenbock": ["wheat", "rich", "fruity"],
  "Bock - Weizendoppelbock": ["wheat", "strong", "complex"],
  "Brett Beer": ["funky", "tart", "wild"],
  "Brown Ale - American": ["nutty", "caramel", "medium-bodied"],
  "Brown Ale - Belgian": ["toasty", "chocolate", "spicy"],
  "Brown Ale - English": ["malty", "nutty", "balanced"],
  "Brown Ale - Imperial / Double": ["bold", "roasted", "robust"],
  "Brown Ale - Other": ["unique", "experimental", "alternative"],
  "California Common": ["amber", "lager", "hoppy"],
  "Chilli / Chile Beer": ["spicy", "hot", "fiery"],
  "Cider - Dry": ["crisp", "tart", "apple"],
  "Cider - Graff": ["apple", "malt", "hybrid"],
  "Cider - Herbed / Spiced / Hopped": ["infused", "botanical", "aromatic"],
  "Cider - Ice / Applewine": ["concentrated", "sweet", "dessert"],
  "Cider - Other Fruit": ["fruity", "alternative", "non-apple"],
  "Cider - Perry / Poire": ["pear", "effervescent", "dry"],
  "Cider - Rose": ["blush", "fruity", "floral"],
  "Cider - Sweet": ["sweet", "juicy", "smooth"],
  "Cider - Traditional / Apfelwein": ["classic", "apple", "traditional"],
  "Corn Beer / Chicha de Jora": ["corn", "indigenous", "traditional"],
  "Cream Ale": ["smooth", "creamy", "light"],
  "Dark Ale": ["rich", "malty", "full-bodied"],
  "Farmhouse Ale - Biere de Coupage": ["blended", "complex", "farmhouse"],
  "Farmhouse Ale - Biere de Garde": ["malt-forward", "cellar-aged", "French"],
  "Farmhouse Ale - Biere de Mars": ["spring", "fruity", "rustic"],
  "Farmhouse Ale - Grisette": ["light", "refreshing", "minerally"],
  "Farmhouse Ale - Other": ["diverse", "experimental", "farmhouse"],
  "Farmhouse Ale - Sahti": ["rye", "spicy", "Finnish"],
  "Farmhouse Ale - Saison": ["dry", "spicy", "refreshing"],
  Festbier: ["malty", "crisp", "Oktoberfest"],
  "Flavored Malt Beverage": ["sweet", "fruity", "refreshing"],
  "Freeze-Distilled Beer": ["concentrated", "strong", "intense"],
  "Fruit Beer": ["fruity", "refreshing", "flavorful"],
  "Gluten-Free": ["gluten-free", "alternative", "specialty"],
  "Golden Ale - American": ["crisp", "hoppy", "golden"],
  "Golden Ale - English": ["malty", "balanced", "smooth"],
  "Golden Ale - Other": ["light", "easy-drinking", "versatile"],
  "Golden Ale - Ukrainian": ["malty", "bready", "Ukrainian"],
  "Golden Ale - Italian": ["crisp", "refreshing", "Italian"],
  "Grape Ale - Other": ["grape", "fruity", "experimental"],
  "Grodziskie / Gratzer": ["smoky", "crisp", "Polish"],
  Happoshu: ["light", "low-malt", "Japanese"],
  "Hard Ginger Beer": ["spicy", "ginger", "refreshing"],
  "Hard Kombucha / Jun": ["fermented", "effervescent", "tea"],
  "Hard Seltzer": ["crisp", "light", "refreshing"],
  "Historical Beer - Adambier": ["smoky", "rich", "historical"],
  "Historical Beer - Berliner Braunbier": ["tart", "malty", "historical"],
  "Historical Beer - Broyhan": ["citrusy", "herbal", "historical"],
  "Historical Beer - Burton Ale": ["English", "balanced", "historical"],
  "Historical Beer - Dampfbier": ["yeasty", "malty", "historical"],
  "Historical Beer - Gruit / Ancient Herbed Ale": [
    "herbal",
    "spiced",
    "historical",
  ],
  "Historical Beer - Kentucky Common": ["sour", "corn", "historical"],
  "Historical Beer - Kuit / Kuyt / Koyt": ["grainy", "malty", "historical"],
  "Historical Beer - Lichtenhainer": ["sour", "smoky", "historical"],
  "Historical Beer - Mumme": ["sweet", "spiced", "historical"],
  "Historical Beer - Other": ["unique", "experimental", "historical"],
  "Historical Beer - Steinbier": ["smoky", "caramel", "historical"],
  "Historical Beer - Zoigl": ["amber", "bready", "historical"],
  "Honey Beer": ["sweet", "smooth", "nectar"],
  "IPA - American": ["hoppy", "citrusy", "bold"],
  "IPA - Belgian": ["spicy", "fruity", "yeasty"],
  "IPA - Black / Cascadian Dark Ale": ["roasty", "piney", "dark"],
  "IPA - Brett": ["funky", "wild", "complex"],
  "IPA - Brown": ["toasty", "caramel", "nutty"],
  "IPA - Brut": ["dry", "effervescent", "crisp"],
  "IPA - Cold": ["crisp", "refreshing", "cooling"],
  "IPA - English": ["balanced", "earthy", "traditional"],
  "IPA - Farmhouse": ["spicy", "fruity", "rustic"],
  "IPA - Fruited": ["fruity", "tropical", "juicy"],
  "IPA - Imperial / Double": ["strong", "resinous", "intense"],
  "IPA - Imperial / Double Black": ["bold", "roasty", "dark"],
  "IPA - Imperial / Double Milkshake": ["creamy", "sweet", "indulgent"],
  "IPA - Imperial / Double New England / Hazy": ["hazy", "juicy", "tropical"],
  "IPA - Milkshake": ["sweet", "creamy", "fruity"],
  "IPA - New England / Hazy": ["hazy", "juicy", "citrusy"],
  "IPA - Other": ["unique", "experimental", "alternative"],
  "Lager - Amber / Red": ["caramel", "malty", "toasty", "lager"],
  "Lager - American": ["crisp", "clean", "refreshing", "lager"],
  "Lager - American Amber / Red": ["caramel", "malty", "balanced", "lager"],
  "Lager - American Light": ["light", "crisp", "easy-drinking", "lager"],
  "Lager - Dark": ["toasty", "malty", "smooth"],
  "Lager - Dortmunder / Export": ["crisp", "bready", "balanced", "lager"],
  "Lager - IPL (India Pale Lager)": ["hoppy", "crisp", "balanced", "lager"],
  "Lager - Mexican": ["crisp", "light", "refreshing", "lager", "Lager"],
  "Lager - Pale": ["crisp", "clean", "golden", "lager"],
  "Malt Beer": ["malty", "toasty", "nutty"],
  "Pale Ale - American": ["hoppy", "citrusy", "balanced", "paleale"],
  "Pale Ale - Australian": ["bitter", "fruity", "hop-forward", "paleale"],
  "Pale Ale - Belgian": ["spicy", "fruity", "yeasty", "paleale"],
  "Pale Ale - English": ["malty", "balanced", "biscuity", "paleale"],
  "Pale Ale - Milkshake": ["sweet", "creamy", "fruity", "paleale"],
  "Pilsner - German": ["crisp", "clean", "grassy", "pilsner"],
  "Pilsner - Czech/Bohemian": ["refreshing", "hoppy", "bready", "pilsner"],
  "Pilsner - Imperial / Double": ["bold", "hoppy", "crisp", "pilsner"],
  "Pilsner - Italian": ["crisp", "malty", "European", "pilsner"],
  "Stout - American": ["roasty", "bittersweet", "full-bodied", "stout"],
  "Stout - Belgian": ["dark", "rich", "fruity", "stout"],
  "Stout - Coffee": ["roasty", "bittersweet", "coffee-infused", "stout"],
  "Stout - English": [
    "roasty",
    "creamy",
    "balanced",
    "stout",
    "stout",
    "english",
  ],
  "Stout - Imperial / Double": [
    "bold",
    "roasty",
    "full-bodied",
    "stout",
    "imperial",
  ],
  "Stout - Imperial / Double Coffee": [
    "bold",
    "roasty",
    "coffee-forward",
    "stout",
    "imperial",
  ],
  "Strong Ale - American": ["robust", "hoppy", "full-bodied"],
  "Strong Ale - English": ["malty", "balanced", "rich"],
  "Strong Ale - Other": ["complex", "full-bodied", "strong"],
  "Wheat Beer": ["refreshing", "spicy", "light"],
};

const getAllKeys = () => {
  return Object.keys(keywordMappings);
};

module.exports = {
  getAllKeys,
  keywordMappings,
};
